name: Daily Commit
on:
  schedule:
    - cron: '0 4 * * *' # 每天 UTC 10:00（台灣時間 18:00）執行

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update daily log
        run: echo "$(date)" >> daily_log.txt

      - name: Commit and push
        run: |
          git config --global user.name "你的GitHub帳號"
          git config --global user.email "你的GitHub信箱"
          git add .
          git commit -m "每日自動更新 $(date)"
          git push
